### ISSUE TITLE
可以显示在其他Activity上面吗？

### ISSUE THREAD

**Issue by ghost** [o0o0oo00/Pudding#1]
Activity A调用show，当前界面为Activity B，当前界面能否显示到

**Comment by o0o0oo00** [comment]
想要使得弹出的View不与Activity耦合，也就是系统级的弹窗，那么必然是需要申请系统权限的。
如果不申请权限，我们使用的WindowManger添加的view是属于Activity的层级的（层级 < 2000）。
就是每个Activity有他自己的PuddingView。
当Activity A调用show再启动了Activity B ，此时Activity A的Pudding 并没消失，而是被Activity B挡住了。当我们返回Activity A的时候Pudding依然在。
当我们finish()  Activity A的时候，Pudding会随着 Activity一起销毁掉，也就不展示了。
