### ISSUE TITLE
在显示过程中如果键盘弹出状态会出现这种情况

### ISSUE THREAD

**Issue by isliuqihang** [o0o0oo00/Pudding#4]
![微信图片_20191219182414](https://user-images.githubusercontent.com/16540388/71166058-e4589d80-228c-11ea-9cef-5166a70e13eb.jpg)

**Comment by o0o0oo00** [comment]
感谢反馈，问题已经得到解决
在WindowManager.LayoutParams的flag需要如下两条配合使用
WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE or WindowManager.LayoutParams.FLAG_ALT_FOCUSABLE_IM
已经更新了小版本
   implementation 'com.github.o0o0oo00:Pudding:1.2.1'
